services:
  dns-server:
    container_name: dns-test
    hostname: dns-test
    build:
      context: .
      dockerfile: Dockerfile
    image: technitium-fork:test
    ports:
      - "15353:53/udp"    # DNS service (UDP)
      - "15353:53/tcp"    # DNS service (TCP)
      - "1443:443/udp"    # DNS-over-HTTPS (HTTP/3)
      - "1443:443/tcp"    # DNS-over-HTTPS (HTTP/1.1, HTTP/2)
      - "1853:853/udp"    # DNS-over-QUIC
      - "1853:853/tcp"    # DNS-over-TLS
      - "15380:5380/tcp"  # DNS web console (HTTP)
      - "13443:53443/tcp" # DNS web console (HTTPS)
    environment:
      - DNS_SERVER_DOMAIN=dns-test
      - DNS_SERVER_LOG_FOLDER_PATH=/var/log/technitium/dns
    volumes:
      - config:/etc/dns
      - logs:/var/log/technitium/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535

volumes:
  config:
  logs:
